### ISSUE TITLE
Where to add this jar in the kafka connect container

### ISSUE THREAD

**Issue by agonzale34** [canelmas/kafka-connect-field-and-time-partitioner#1]
Hi, thanks for sharing this project, currently I'm trying to implement this partitioner in a Kafka connect standalone, but currently, I'm getting an error when running the service, looks like I'm not placing the jar in the correct folder, I wonder if you may indicate how you configure this partitioner in your Kafka connect service.

**Comment by canelmas** [comment]
Hi @agonzale34, I believe you have to put the jar under the plugin directory. 

So assuming that you have CONNECT_PLUGIN_PATH = /usr/share/java env var set, you may put it under /usr/share/java/kafka-connect-s3 or /usr/share/java/kafka-connect-storage-common. They should both work fine.

Let me know how it goes.

**Comment by canelmas** [comment]
a working compose yml may look like :

```yml
kconnect:
    image: confluentinc/cp-kafka-connect:5.2.1
    .....
    environment:
      ......
      CONNECT_PLUGIN_PATH: /usr/share/java
    volumes:
      - ${DIRECTORY_TO_THIS_JAR}:/usr/share/java/kafka-connect-s3/this-new-custom-partitioner
```
```env
# .env
DIRECTORY_TO_THIS_JAR=~/time-field-based-partitioner
```

```bash
tree time-field-based-partitioner
time-field-based-partitioner
└── connect-s3-fieldandtime-partitioner-1.0.0-SNAPSHOT.jar
```
